#!/bin/bash
# env.sh — shared environment for all unattended BUDDY runs (launchd has a bare env).
# Sourced by run-buddy.sh, call-sweep.sh, prep-sweep.sh. Do not run directly.
#
# PORTABLE: this file is identical on every machine. Anything machine-specific
# (the exact PATH to pi/quick/jq) lives in env.local.sh, which install.sh generates
# and which is gitignored. Never hardcode a home directory or nix hash here.

# --- Home (launchd sets HOME for user agents; fall back just in case) ---
export HOME="${HOME:-$(eval echo ~"$(whoami)")}"

# --- Base PATH, then layer machine-specific dirs from env.local.sh ---
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.local/bin:$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin"

# --- Paths ---
export BUDDY_DIR="$HOME/buddy-scheduler"
export BUDDY_LOGS="$BUDDY_DIR/logs"
export BUDDY_STATE="$BUDDY_DIR/state"
export BUDDY_CREDS="$BUDDY_DIR/creds.env"
export TOKEN_CACHE="$HOME/.cache/tool-gateway-token"

# --- Machine-specific PATH additions (generated by install.sh; gitignored) ---
if [ -f "$BUDDY_DIR/env.local.sh" ]; then
  # shellcheck disable=SC1090
  . "$BUDDY_DIR/env.local.sh"
fi

# --- Model for the around-call sweep (mid model = good writing, cheap on the 15-min heartbeat).
# Quality jobs (morning/eod/weekly) use whatever your pi default model is.
export BUDDY_MODEL_SWEEP="${BUDDY_MODEL_SWEEP:-claude-sonnet-4-6}"

mkdir -p "$BUDDY_LOGS" "$BUDDY_STATE"

# --- Load snapshotted model-proxy creds (produced by link-creds.sh) ---
if [ -f "$BUDDY_CREDS" ]; then
  # shellcheck disable=SC1090
  set -a; . "$BUDDY_CREDS"; set +a
  [ -n "${PI_PROXY_API_KEY_B64:-}" ]     && export PI_PROXY_API_KEY="$(printf '%s' "$PI_PROXY_API_KEY_B64" | base64 -d)"
  [ -n "${PI_PROXY_AUTH_HEADER_B64:-}" ] && export PI_PROXY_AUTH_HEADER="$(printf '%s' "$PI_PROXY_AUTH_HEADER_B64" | base64 -d)"
  [ -n "${PI_PROXY_BASE_URL_B64:-}" ]    && export PI_PROXY_BASE_URL="$(printf '%s' "$PI_PROXY_BASE_URL_B64" | base64 -d)"
fi
