#!/bin/bash
# link-creds.sh — snapshot the model-proxy credentials that unattended runs need.
#
# WHY: PI_PROXY_API_KEY / PI_PROXY_AUTH_HEADER are injected into a live pi/dev
# session by the Pi Desktop launcher. launchd jobs don't have them. This captures
# the current session's values into creds.env (chmod 600) so scheduled runs can auth.
#
# RUN THIS FROM INSIDE A LIVE PI SESSION (or a shell that has the vars), e.g. ask
# BUDDY: "re-link my scheduler creds" — or run `bash ~/buddy-scheduler/link-creds.sh`.
#
# Re-run whenever scheduled jobs start failing model auth (creds rotated).

set -euo pipefail
DIR="$HOME/buddy-scheduler"
CREDS="$DIR/creds.env"
mkdir -p "$DIR"

missing=""
[ -n "${PI_PROXY_API_KEY:-}" ]     || missing="$missing PI_PROXY_API_KEY"
[ -n "${PI_PROXY_AUTH_HEADER:-}" ] || missing="$missing PI_PROXY_AUTH_HEADER"
if [ -n "$missing" ]; then
  echo "❌ Missing:$missing"
  echo "   You must run this from a live pi/dev session that has these vars set."
  exit 1
fi

# Base64-encode values so spaces / special chars survive shell sourcing.
b64(){ printf '%s' "$1" | base64 | tr -d '\n'; }
umask 077
{
  echo "# Auto-generated by link-creds.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo "# Model-proxy creds for unattended BUDDY runs. chmod 600. Do not commit."
  echo "# Values are base64-encoded; env.sh decodes them."
  echo "PI_PROXY_API_KEY_B64=$(b64 "${PI_PROXY_API_KEY}")"
  echo "PI_PROXY_AUTH_HEADER_B64=$(b64 "${PI_PROXY_AUTH_HEADER}")"
  echo "PI_PROXY_BASE_URL_B64=$(b64 "${PI_PROXY_BASE_URL:-}")"
  echo "BUDDY_CREDS_EPOCH=$(date +%s)"
} > "$CREDS"
chmod 600 "$CREDS"

echo "✅ Linked creds → $CREDS (chmod 600)"
echo "   Tool-gateway token cache: $HOME/.cache/tool-gateway-token"
if [ -f "$HOME/.cache/tool-gateway-token" ]; then
  age_days=$(( ( $(date +%s) - $(stat -f %m "$HOME/.cache/tool-gateway-token") ) / 86400 ))
  echo "   Token age: ${age_days}d (tools will fail if this expires — refresh by opening pi normally)."
else
  echo "   ⚠️ Token cache missing — MCP tools (CRM/BQ) will fail until you open pi normally once."
fi
