#!/bin/bash
# install.sh — set up YOUR own instance of BUDDY + Cockpit.
# Idempotent-ish: backs up anything it would overwrite. Never copies anyone else's creds.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
say(){ printf "\n\033[1;32m▸ %s\033[0m\n" "$1"; }
ask(){ # ask "Prompt" "default" -> echoes answer
  local p="$1" d="${2:-}" a
  if [ -n "$d" ]; then read -r -p "$p [$d]: " a; echo "${a:-$d}"
  else read -r -p "$p: " a; echo "$a"; fi
}
ts(){ date +%Y%m%d-%H%M%S; }
backup(){ [ -e "$1" ] && mv "$1" "$1.bak-$(ts)" && echo "   (backed up existing → $1.bak-$(ts))" || true; }

echo "╔══════════════════════════════════════════╗"
echo "║   BUDDY Starter Kit — personal installer   ║"
echo "╚══════════════════════════════════════════╝"
echo "This sets up BUDDY to run as YOU. It never uses anyone else's credentials —"
echo "your CRM, Gmail, calendar and BigQuery all authenticate as your own Shopify account."

say "Running preflight"
bash "$HERE/preflight.sh" || { echo "Preflight failed — resolve the ❌ items first."; exit 1; }

# ---------- gather identity ----------
say "Tell BUDDY who you are (5 quick questions)"
DEF_HANDLE="$(git config user.email 2>/dev/null | cut -d@ -f1)"; DEF_HANDLE="${DEF_HANDLE:-$(whoami)}"
NAME="$(ask 'Your full name' "$(id -F 2>/dev/null || echo "")")"
ROLE="$(ask 'Your role' 'Account Executive')"
REGION="$(ask 'Your region' '')"
BASED="$(ask 'Based (city, timezone)' '')"
MANAGER="$(ask 'Your manager' '')"
TARGET="$(ask 'Annual target (e.g. $850,000)' '')"
HANDLE="$(ask 'Short handle for your cockpit URL (a-z0-9-)' "$DEF_HANDLE")"
HANDLE="$(echo "$HANDLE" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')"
COCKPIT_HANDLE="${HANDLE}-buddy-cockpit"
echo
echo "Your CRM owner_id powers §1/§2 (the owned-deal roster). If you don't know it, leave blank —"
echo "BUDDY can find it later (ask it: \"what's my CRM owner_id?\")."
OWNER_ID="$(ask 'CRM owner_id (optional)' '')"

echo
echo "Review:"
echo "  Name:      $NAME"
echo "  Role:      $ROLE     Region: $REGION"
echo "  Based:     $BASED    Manager: $MANAGER"
echo "  Target:    $TARGET"
echo "  Cockpit:   https://${COCKPIT_HANDLE}.quick.shopify.io"
echo "  owner_id:  ${OWNER_ID:-<to fill later>}"
CONFIRM="$(ask 'Proceed? (y/n)' 'y')"; [ "$CONFIRM" = "y" ] || { echo "Aborted."; exit 0; }

# ---------- 1. skill ----------
say "Installing Buddy skill → ~/.pi/agent/skills/buddy"
mkdir -p "$HOME/.pi/agent/skills"
backup "$HOME/.pi/agent/skills/buddy"
cp -R "$HERE/payload/skill/buddy" "$HOME/.pi/agent/skills/buddy"

# ---------- 2. AGENTS.md ----------
say "Writing your AGENTS.md → ~/.pi/agent/AGENTS.md"
mkdir -p "$HOME/.pi/agent"
backup "$HOME/.pi/agent/AGENTS.md"
sed -e "s|{{NAME}}|${NAME}|g" -e "s|{{ROLE}}|${ROLE}|g" -e "s|{{REGION}}|${REGION}|g" \
    -e "s|{{BASED}}|${BASED}|g" -e "s|{{MANAGER}}|${MANAGER}|g" -e "s|{{TARGET}}|${TARGET}|g" \
    -e "s|{{OWNER_ID}}|${OWNER_ID:-TODO}|g" -e "s|{{HANDLE}}|${HANDLE}|g" \
    "$HERE/templates/AGENTS.md.template" > "$HOME/.pi/agent/AGENTS.md"

# ---------- 3. scheduler ----------
say "Installing scheduler → ~/buddy-scheduler"
mkdir -p "$HOME/buddy-scheduler/logs" "$HOME/buddy-scheduler/state"
for f in "$HERE"/payload/buddy-scheduler/*; do
  base="$(basename "$f")"
  backup "$HOME/buddy-scheduler/$base"
  cp "$f" "$HOME/buddy-scheduler/$base"
done
chmod +x "$HOME/buddy-scheduler/"*.sh 2>/dev/null || true

# machine-specific PATH → env.local.sh (gitignored, per-machine)
say "Detecting tool paths for the always-on runner (env.local.sh)"
PATHDIRS=""
for bin in pi quick jq node base64; do
  d="$(command -v "$bin" 2>/dev/null | xargs -I{} dirname {} 2>/dev/null || true)"
  [ -n "$d" ] && case ":$PATHDIRS:" in *":$d:"*) ;; *) PATHDIRS="${PATHDIRS:+$PATHDIRS:}$d";; esac
done
{
  echo "# env.local.sh — machine-specific PATH additions (generated by install.sh)."
  echo "# Gitignored. Regenerate by re-running install.sh if you move/upgrade tools."
  echo "export PATH=\"${PATHDIRS}:\$PATH\""
} > "$HOME/buddy-scheduler/env.local.sh"
echo "   PATH dirs: ${PATHDIRS}"

# ---------- 4. cockpit ----------
say "Installing cockpit → ~/Desktop/buddy-site/buddy-cockpit"
mkdir -p "$HOME/Desktop/buddy-site/buddy-cockpit"
for f in "$HERE"/payload/cockpit/*; do
  base="$(basename "$f")"
  backup "$HOME/Desktop/buddy-site/buddy-cockpit/$base"
  cp "$f" "$HOME/Desktop/buddy-site/buddy-cockpit/$base"
done
# personalise
sed -i '' -e "s|__NAME__|${NAME}|g" "$HOME/Desktop/buddy-site/buddy-cockpit/index.html"
sed -i '' -e "s|__COCKPIT_HANDLE__|${COCKPIT_HANDLE}|g" "$HOME/Desktop/buddy-site/buddy-cockpit/deploy.sh"
chmod +x "$HOME/Desktop/buddy-site/buddy-cockpit/deploy.sh"

# ---------- 5. launchd (macOS only) ----------
if [ "$(uname)" = "Darwin" ]; then
  say "Setting up the always-on scheduler (launchd)"
  PLIST="$HOME/Library/LaunchAgents/io.buddy.dispatch.plist"
  launchctl unload "$PLIST" 2>/dev/null || true
  backup "$PLIST"
  sed -e "s|__HOME__|${HOME}|g" "$HERE/templates/io.buddy.dispatch.plist.template" > "$PLIST"
  launchctl load "$PLIST" && echo "   launchd agent loaded (heartbeat every 15 min)."
else
  say "Skipping launchd (not macOS). Run 'gm' in pi manually each morning."
fi

# ---------- 6. creds link (best-effort; only works inside a live pi session) ----------
say "Linking model-proxy creds for unattended runs"
if [ -n "${PI_PROXY_API_KEY:-}" ] && [ -n "${PI_PROXY_AUTH_HEADER:-}" ]; then
  bash "$HOME/buddy-scheduler/link-creds.sh" || echo "   (link-creds reported an issue — you can re-run it later)"
else
  echo "   ⚠️  Not inside a live pi session, so scheduled runs can't auth yet."
  echo "      Open pi normally, then say: \"re-link my scheduler creds\" (runs link-creds.sh)."
fi

# ---------- 7. deploy cockpit ----------
say "Deploying your cockpit"
( cd "$HOME/Desktop/buddy-site/buddy-cockpit" && ./deploy.sh ) || echo "   (deploy skipped/failed — run ./deploy.sh yourself, or just say 'gm')"

# ---------- done ----------
cat <<EOF

╔══════════════════════════════════════════╗
║              ✅  BUDDY installed            ║
╚══════════════════════════════════════════╝
Your cockpit:  https://${COCKPIT_HANDLE}.quick.shopify.io

Next steps:
  1. Open pi.
  2. Say:  gm
     → BUDDY runs your morning routine, builds your roster from YOUR CRM,
       and populates your cockpit.
  3. If scheduled runs can't auth yet, say: "re-link my scheduler creds".

Everything external is draft-only — BUDDY never sends on its own. Enjoy. 🎁
EOF
